[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[start]
cmd = "mkdir -p staticfiles media && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py setup_inicial && gunicorn setup.wsgi --bind 0.0.0.0:$PORT --timeout 120 --workers 2"
