# Generated by Django 3.2.25 on 2026-06-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurarEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor_smtp', models.CharField(default='smtp.zoho.com.br', max_length=200)),
                ('porta', models.IntegerField(default=587)),
                ('usuario', models.EmailField(default='dev@anagma.com.br', max_length=254)),
                ('senha', models.CharField(blank=True, help_text='Senha ou senha de aplicativo do Zoho Mail', max_length=200, null=True)),
                ('use_tls', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Email',
                'verbose_name_plural': 'Configurações de Email',
            },
        ),
    ]
