# Generated by Django 6.0.6 on 2026-06-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuraremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraremail',
            name='use_ssl',
            field=models.BooleanField(default=True, help_text='SSL direto — porta 465 (recomendado Zoho)'),
        ),
        migrations.AlterField(
            model_name='configuraremail',
            name='porta',
            field=models.IntegerField(default=465),
        ),
        migrations.AlterField(
            model_name='configuraremail',
            name='servidor_smtp',
            field=models.CharField(default='smtp.zoho.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='configuraremail',
            name='use_tls',
            field=models.BooleanField(default=False, help_text='STARTTLS — porta 587'),
        ),
    ]
