# Generated by Django 6.0.6 on 2026-06-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='role',
            field=models.CharField(choices=[('diretor_ti', 'Diretor de Tecnologia'), ('diretor', 'Diretor'), ('dev', 'Analista e Desenvolvedor de Sistemas'), ('analista', 'Analista de Sistema')], default='analista', max_length=20),
        ),
    ]
