# Generated by Django 6.0.6 on 2026-06-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_perfilusuario_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='role',
            field=models.CharField(choices=[('diretor_ti', 'Diretor de Tecnologia'), ('diretor', 'Diretor'), ('coordenador', 'Coordenador'), ('dev', 'Analista e Desenvolvedor de Sistemas'), ('analista', 'Analista de Sistema'), ('usr', 'Usuário')], default='usr', max_length=20),
        ),
    ]
