# Generated by Django 6.0.6 on 2026-06-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_perfilusuario_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
