# Generated by Django 3.2.25 on 2026-06-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_chamado_observadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='email_verificar',
            field=models.BooleanField(default=False, verbose_name='E-mail a verificar'),
        ),
    ]
