# Generated by Django 3.2.25 on 2026-06-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20260610_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='avatares/', verbose_name='Foto de perfil'),
        ),
    ]
