# Generated by Django 6.0.6 on 2026-06-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_configuraremail_remetente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraremail',
            name='senha',
            field=models.CharField(blank=True, help_text='Senha ou senha de aplicativo', max_length=200, null=True),
        ),
    ]
