# Generated by Django 6.0.6 on 2026-06-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_configuraremail_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraremail',
            name='usar_api',
            field=models.BooleanField(default=False, help_text='Envia via API HTTP (ignora SMTP). Use quando a porta SMTP estiver bloqueada pelo provedor.', verbose_name='Usar API HTTP'),
        ),
    ]
