# Generated by Django 6.0.6 on 2026-06-15 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preencher_fechado_em(apps, schema_editor):
    Chamado = apps.get_model('core', 'Chamado')
    Chamado.objects.filter(status='fechado', fechado_em__isnull=True).update(fechado_em=models.F('atualizado_em'))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_configuraremail_usar_api'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='fechado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chamado',
            name='excluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='excluido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_excluidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chamado',
            name='motivo_exclusao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(preencher_fechado_em, migrations.RunPython.noop),
    ]
