# Generated by Django 3.2.25 on 2026-06-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_chamado_excluido_chamado_excluido_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='reaberto_count',
            field=models.IntegerField(default=0, verbose_name='Vezes reaberto'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='reaberto_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última reabertura'),
        ),
    ]
