# Generated by Django 3.2.25 on 2026-06-16 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20260616_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLADefinicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do SLA')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], help_text='Cada prioridade pode ter apenas um SLA ativo por vez.', max_length=20, unique=True, verbose_name='Prioridade')),
                ('tempo_limite_horas', models.FloatField(help_text='Limite em horas úteis (seg–sex 08h–18h) para resolução.', verbose_name='Tempo limite (horas úteis)')),
                ('cor_classe', models.CharField(default='bg-emerald-100 text-emerald-800', help_text='Tailwind: bg-{cor}-100 text-{cor}-800', max_length=100, verbose_name='Classe CSS do badge')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Definição de SLA',
                'verbose_name_plural': 'Definições de SLA',
                'ordering': ['prioridade'],
            },
        ),
        migrations.AddField(
            model_name='chamado',
            name='sla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sladefinicao', verbose_name='SLA aplicado'),
        ),
    ]
