# Generated by Django 6.0.6 on 2026-08-24 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20260616_1005'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['ordem_posicao', '-criado_em']},
        ),
        migrations.AddField(
            model_name='projeto',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_previsao_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Previsão de Entrega'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='ordem_posicao',
            field=models.IntegerField(default=0, verbose_name='Posição na Coluna'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='responsavel_lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_liderados', to=settings.AUTH_USER_MODEL, verbose_name='Líder / Responsável'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to='core.sistema'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='status_macro',
            field=models.CharField(choices=[('backlog', '📋 Backlog'), ('sprint', '🏃 Sprint Atual'), ('em_construcao', '🔨 Em Construção'), ('homologacao', '🧪 Homologação'), ('concluido', '✅ Concluído')], default='backlog', max_length=20, verbose_name='Status no Kanban'),
        ),
    ]
