# Generated by Django 3.2.25 on 2026-08-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_projeto_options_projeto_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='status_macro',
            field=models.CharField(choices=[('backlog', 'Backlog Geral'), ('sprint', 'Sprint Atual'), ('em_construcao', 'Em Construção'), ('homologacao', 'Homologação / Testes'), ('concluido', 'Em Produção / Concluído')], default='backlog', max_length=20, verbose_name='Status no Kanban'),
        ),
    ]
